### ISSUE TITLE
Decode.float fails to decode large floats

### ISSUE THREAD

**Issue by ajuch** [thoth-org/Thoth.Json#212]
Serializing and deserializing Double.MaxValue works in general:

```f#
open System
open Thoth.Json.Net
Encode.float Double.MaxValue |> Encode.toString 0 |> Decode.fromString Decode.float
val it: Result<float,string> = Ok 1.797693135e+308

match it with Ok f -> f = System.Double.MaxValue | Error e -> failwith "error"
val it: bool = true
```

But in our case we are storing the JSON in a Postgres database in a JSONB-column. Postgres uses the numeric type for numeric JSON values. Fetching the JSON from the database and deserializing it with Thoth.Json leads to a problem:

```sql
select (jsonb('1.7976931348623157E+308'))::text
-- 179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

```f#
let maxFloat = "179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
val maxFloat: string =
  "1797693134862315700000000000000000000000000000000000000000000"+[248 chars]

match Decode.fromString Decode.float maxFloat with Ok f -> f = Double.MaxValue | Error e -> failwith "error"
System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Thoth.Json.Net.Decode.float(String path, JToken token)
   at Thoth.Json.Net.Decode.fromValue[T](String path, FSharpFunc`2 decoder, JToken value)
   at Thoth.Json.Net.Decode.fromString[T](FSharpFunc`2 decoder, String value)
   at <StartupCode$FSI_0026>.$FSI_0026.main@() in C:\stdin:line 3
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Aufgrund eines Fehlers beendet
```

Several other methods to deserialize this value to float worked:

```f#
let parsed = System.Double.Parse "179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
val parsed: float = 1.797693135e+308

parsed = System.Double.MaxValue
val it: bool = true
```

```f#
let parsed = Newtonsoft.Json.JsonConvert.DeserializeObject<float>("179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000")
val parsed: float = 1.797693135e+308

parsed = System.Double.MaxValue
val it: bool = true
```

```f#
System.Text.Json.JsonSerializer.Deserialize<float>("179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000")
val it: float = 1.797693135e+308

parsed = System.Double.MaxValue
val it: bool = true
```

So I consider this a bug, although I would be happier if postgres just returned the value in exponential notation. Please note that the value doesn't need to be that high, it fails also for smaller inputs. It seems somewhere in the loop the value is deserialized as BigInteger, which doesn't implement IConvertible.

**Comment by njlr** [comment]
This appears to be working in `Thoth.Json.Core`?

```fsharp
#r "nuget: Thoth.Json.Core, 0.9.0"
#r "nuget: Thoth.Json.System.Text.Json, 0.3.0"

open Thoth.Json.Core
open Thoth.Json.System.Text.Json

let maxFloat = "179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"

Decode.fromString Decode.float maxFloat
|> printfn "%A"

(*

Ok 1.797693135e+308

*)
```

**Comment by MangelMaxime** [comment]
@njlr The reason why your version works is because you are using `System.Text.Json` instead of `Newtonsoft` under the hood.

However, I am not sure how we could fix `Newtonsoft` to support this scenario.

**Comment by njlr** [comment]
> [@njlr](https://github.com/njlr) The reason why your version works is because you are using `System.Text.Json` instead of `Newtonsoft` under the hood.
> 
> However, I am not sure how we could fix `Newtonsoft` to support this scenario.

Ah yes, I do see the bug with `Newtonsoft`:

```fsharp
#r "nuget: Thoth.Json.Core, 0.9.0"
#r "nuget: Thoth.Json.Newtonsoft, 0.4.0"

open Thoth.Json.Core
open Thoth.Json.Newtonsoft

let maxFloat = "179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"

Decode.fromString Decode.float maxFloat
|> printfn "%A"
```

One fix is to always decode floats via strings (similar to approach in https://github.com/thoth-org/Thoth.Json/pull/244):

```fsharp
#r "nuget: Thoth.Json.Core, 0.9.0"
#r "nuget: Thoth.Json.Newtonsoft, 0.4.0"

open Thoth.Json.Core
open Thoth.Json.Newtonsoft

module Decode =

    open System
    open System.Globalization

    let float' : Decoder<float> =
      {
        new Decoder<float> with
          member _.Decode(helpers, value) =
            if helpers.isNumber(value) then
              let rawString = helpers.anyToString(value)

              match Double.TryParse(rawString, NumberStyles.Float, CultureInfo.InvariantCulture) with
              | true, f -> Ok f
              | false, _ -> ("", BadPrimitive("a float", value)) |> Error
            elif helpers.isString(value) then
              let rawString = helpers.asString(value)

              match Double.TryParse(rawString, NumberStyles.Float, CultureInfo.InvariantCulture) with
              | true, f -> Ok f
              | false, _ -> ("", BadPrimitive("a float", value)) |> Error
            else
              ("", BadPrimitive("a float", value)) |> Error
      }

let maxFloat = "179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"

Decode.fromString Decode.float' maxFloat
|> printfn "%A"

(*

Ok 1.797693135e+308

*)
```

The issue is that each JSON backend will represent numbers with a different precision. 
The only form that does not lose precision is the string representation.

**Comment by MangelMaxime** [comment]
I think I am fine with doing that in Thoth.Json.Core we will however need to advertise that we are making breaking changes in the representation of the types in case people stored it in Database.

If needed they should be able to make a migration script using Thoth.Json and later Thoth.Json.Core. Or even using their own encoders and registering them in the Auto API as it is now able to override any types.

We will need to make a list of the modified types as a reference. And this means that for `Option` and `Date`, we could also decide to use the better default aka (lossless and ISO 8601 (still to be implemented)).
